"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "QuantUS"
DATA_FILES = []
OPTIONS = {
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Quantitative Ultrasound Tool",
        'CFBundleVersion': "0.0.1",
        'CFBundleShortVersionString': "0.1.0"
    },
    'includes': ['ctypes', 'libffi'],
    'iconfile': 'transducer.icns'
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
